name: Introduktion till programmering

description: Introduktion till programmering för IA

author:
    name: Anton Tibblin & Fredrik Ohlin

url: http://mah-webb.github.io

highlighter: pygments

markdown: kramdown

exclude: ['Gemfile', 'Gemfile.lock', 'README.md']

include: ['.htaccess']

permalink: /blog/:title.html
